sudo: required
services:
  - docker

before_install:
  - docker build -t apasashkov/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true apasashkov/react-test npm run test -- --coverage

after_success:
  - docker build -t apasashkov/multi-client ./client
  - docker build -t apasashkov/multi-nginx ./nginx
  - docker build -t apasashkov/multi-server ./server
  - docker build -t apasashkov/multi-worker ./worker
# Log into the docker CLI
# This means take DOCKER_PASSWORD env var, print it in echo and push it through PIPE | to
# stdin of another command. ANother command takes login from DOCKER_ID env var and password
# from stdin. This is done to make login to docker hub with a single command
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push apasashkov/multi-client
  - docker push apasashkov/multi-nginx 
  - docker push apasashkov/multi-server
  - docker push apasashkov/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-multi'
  env: 'Dockermulti-env'
  bucket_name: 'elasticbeanstalk-us-east-1-879533672673'
  bucket_path: 'multi-docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
